# Generated by Django 4.0.3 on 2022-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWebmedic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
